version: "3.9"
services:
  backend:
    build: ./backend
    image: zephyrus2/backend-blogio
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    image: zephyrus2/frontend-blogio
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app